services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    container_name: postgres16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728  # 128MB

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
